"""Cloud-safe LEAN project configuration."""

CONFIG = {'algorithm-name': 'QualityGrowthPi',
 'project-root': '/mnt/nvme_data/shared/quant_gpt',
 'shared-module-root': '/mnt/nvme_data/shared/quant_gpt/src',
 'strategy-config': '/mnt/nvme_data/shared/quant_gpt/src/strategy_settings.py',
 'app-config': '/mnt/nvme_data/shared/quant_gpt/config/app.yaml',
 'settings-profile': 'default',
 'runtime': {'backtest_start_date': '2018-01-01',
             'initial_cash': 100000.0,
             'bootstrap_history_days': 105,
             'stale_data_max_age_minutes': 30,
             'fine_universe_limit': 1000,
             'cloud_audit_logging': True},
 'strategy': {'algorithm_name': 'QualityGrowthPi',
              'benchmark_symbol': 'SPY',
              'rebalance': {'frequency': 'weekly',
                            'anchor_symbol': 'SPY',
                            'after_open_minutes': 30,
                            'max_holdings': 10,
                            'candidate_pool_multiplier': 3},
              'universe': {'exchange_id': 'NYS',
                           'min_market_cap': 5000000000,
                           'min_price': 10.0,
                           'require_fundamental_data': True},
              'thresholds': {'roe_min': 0.15,
                             'gross_margin_min': 0.3,
                             'debt_to_equity_min': 0.0,
                             'debt_to_equity_max': 1.5,
                             'revenue_growth_min': 0.1,
                             'net_income_growth_min': 0.1,
                             'pe_ratio_min': 5.0,
                             'peg_ratio_min': 0.0,
                             'peg_ratio_max': 2.0,
                             'sector_percentile_min': 0.7},
              'weights': {'roe': 0.3,
                          'revenue_growth': 0.3,
                          'net_income_growth': 0.2,
                          'inverse_peg': 0.2,
                          'fundamental_component': 0.7,
                          'timing_component': 0.3,
                          'timing_relative_volume': 0.3,
                          'timing_volatility_contraction': 0.4,
                          'timing_trend': 0.3},
              'timing': {'volume_window': 20,
                         'price_window': 20,
                         'short_sma': 20,
                         'long_sma': 100,
                         'relative_volume_threshold': 1.2,
                         'volatility_contraction_threshold': 0.75}},
 'notes': ['src/strategy_settings.py is the single source of truth for '
           'parameters that move backtest outputs.',
           'The LEAN cloud entrypoint is intentionally self-contained and does '
           'not rely on repo-level Python packages.',
           'Use scripts/sync_lean_project.sh after changing strategy settings '
           'or QUANT_GPT_SETTINGS_PROFILE.'],
 'local-id': 908507761}
