"""Cloud-safe LEAN project configuration."""

CONFIG = {
    "algorithm-name": "GraphStatArb",
    "project-root": "/mnt/nvme_data/shared/quant_gpt",
    "shared-module-root": "/mnt/nvme_data/shared/quant_gpt/src",
    "strategy-config": "/mnt/nvme_data/shared/quant_gpt/src/strategy_settings.py",
    "app-config": "/mnt/nvme_data/shared/quant_gpt/config/app.yaml",
    "settings-profile": "default",
    "runtime": {
        "backtest_start_date": "2022-01-01",
        "initial_cash": 100000.0,
        "bootstrap_history_days": 120,
        "stale_data_max_age_minutes": 30,
        "fine_universe_limit": 12,
        "cloud_audit_logging": True,
    },
    "strategy": {
        "algorithm_name": "GraphStatArb",
        "benchmark_symbol": "SPY",
        "universe": {
            "symbols": [
                "AAPL",
                "MSFT",
                "NVDA",
                "AVGO",
                "AMD",
                "QCOM",
                "META",
                "GOOGL",
                "AMZN",
                "TSM",
                "ADBE",
                "CRM",
            ],
            "lookback_days": 90,
            "min_history_days": 60,
            "min_price": 5.0,
        },
        "graph": {
            "correlation_lookback_days": 60,
            "min_correlation": 0.65,
            "min_cluster_size": 2,
            "max_cluster_size": 6,
            "max_pairs_per_cluster": 2,
        },
        "spread": {
            "zscore_lookback_days": 30,
            "entry_z_score": 1.75,
            "take_profit_z_score": 0.35,
            "stop_loss_z_score": 3.25,
            "max_half_life_days": 20.0,
            "min_correlation_stability": 0.45,
            "min_expected_edge_bps": 18.0,
            "transaction_cost_bps": 5.0,
        },
        "exit_policy": {
            "initial_take_profit_z_score": 0.35,
            "minimum_take_profit_z_score": 0.10,
            "initial_stop_loss_z_score": 3.25,
            "minimum_stop_loss_z_score": 2.10,
            "decay_half_life_days": 8.0,
            "max_holding_days": 15,
        },
        "sizing": {
            "payoff_ratio_floor": 1.0,
            "probability_floor": 0.52,
            "min_fraction": 0.01,
            "max_fraction": 0.12,
            "max_gross_exposure_per_trade": 0.18,
            "max_gross_exposure_total": 1.25,
            "max_net_exposure_total": 0.15,
            "max_open_pairs": 6,
            "max_pairs_per_cluster": 2,
            "overlap_penalty": 0.5,
        },
        "ml_filter": {
            "mode": "embedded_scorecard",
            "model_version": "softvote_v2026_03_08",
            "probability_threshold": 0.58,
            "min_confidence": 0.55,
            "object_store_model_key": "28761844/stat-arb/models/softvote_v2026_03_08/ensemble.joblib",
            "local_model_path": "/mnt/nvme_data/shared/quant_gpt/data/models/stat_arb/ensemble.joblib",
            "feature_schema_version": "stat_arb_v1",
            "fallback_mode": "embedded_scorecard",
            "members": [],
        },
    },
    "notes": [
        "src/strategy_settings.py is the single source of truth for parameters that move stat-arb outputs.",
        "The LEAN cloud entrypoint is intentionally self-contained and mirrors the repo stat-arb math without pydantic.",
        "Use scripts/sync_lean_project.sh after changing stat-arb settings or QUANT_GPT_SETTINGS_PROFILE.",
    ],
}
