#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
TEMPLATE_FILE="$PROJECT_ROOT/.env.template"
TMP_FILE="$(mktemp)"

cleanup() {
  rm -f "$TMP_FILE"
}
trap cleanup EXIT

if [[ ! -f "$TEMPLATE_FILE" ]]; then
  printf 'Missing template file: %s\n' "$TEMPLATE_FILE" >&2
  exit 1
fi

get_existing_value() {
  local key="$1"
  local value=""
  if [[ -f "$ENV_FILE" ]]; then
    value="$(
      python3 - "$ENV_FILE" "$key" <<'PY'
import sys
from pathlib import Path

env_path = Path(sys.argv[1])
key = sys.argv[2]

if not env_path.exists():
    raise SystemExit(0)

for raw_line in env_path.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    lhs, rhs = line.split("=", 1)
    if lhs.strip() != key:
        continue
    rhs = rhs.strip()
    if len(rhs) >= 2 and rhs[0] == rhs[-1] and rhs[0] in {"'", '"'}:
        quote = rhs[0]
        body = rhs[1:-1]
        if quote == "'":
            body = body.replace("'\"'\"'", "'")
        print(body)
    else:
        print(rhs)
    break
PY
    )"
    if [[ -n "$value" ]]; then
      printf '%s' "$value"
      return
    fi
    case "$key" in
      MASSIVE_API_KEY)
        grep -E "^POLYGON_API_KEY=" "$ENV_FILE" | tail -n1 | cut -d'=' -f2- || true
        return
        ;;
      MASSIVE_BASE_URL)
        grep -E "^POLYGON_BASE_URL=" "$ENV_FILE" | tail -n1 | cut -d'=' -f2- || true
        return
        ;;
    esac
  fi
}

quote_env_value() {
  local value="$1"
  printf "'%s'" "${value//\'/\'\"\'\"\'}"
}

prompt_value() {
  local key="$1"
  local prompt="$2"
  local default="$3"
  local secret="$4"
  local existing value

  existing="$(get_existing_value "$key")"
  value="$existing"

  if [[ -n "$existing" ]]; then
    read -r -p "$key already exists. Keep current value? [Y/n]: " keep
    if [[ ! "$keep" =~ ^[Nn]$ ]]; then
      printf '%s=%s\n' "$key" "$(quote_env_value "$existing")" >> "$TMP_FILE"
      printf -v "$key" '%s' "$existing"
      export "$key"
      return
    fi
  fi

  if [[ "$secret" == "true" ]]; then
    read -r -s -p "$prompt [$default]: " value
    printf '\n'
  else
    read -r -p "$prompt [$default]: " value
  fi

  if [[ -z "$value" ]]; then
    value="$default"
  fi
  printf '%s=%s\n' "$key" "$(quote_env_value "$value")" >> "$TMP_FILE"
  printf -v "$key" '%s' "$value"
  export "$key"
}

printf '# Generated by scripts/setup_env.sh on %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "$TMP_FILE"

prompt_value "QUANT_GPT_ENV" "Environment name" "dev" "false"
prompt_value "QUANT_GPT_RUNTIME_ROOT" "Runtime root path" "/mnt/nvme_data/shared/quant_gpt" "false"
prompt_value "QUANT_GPT_STATE_DB" "SQLite DB path" "/mnt/nvme_data/shared/quant_gpt/state/quant_gpt.db" "false"
prompt_value "QUANT_GPT_LOG_LEVEL" "Log level" "DEBUG" "false"
prompt_value "QUANT_GPT_STRATEGY_MODE" "Strategy mode (quality_growth or stat_arb_graph_pairs)" "quality_growth" "false"
prompt_value "QUANT_GPT_PROVIDER_MODE" "Provider mode" "external_equivalent" "false"
prompt_value "QUANT_GPT_ENABLE_LLM" "Enable LLM subsystem" "true" "false"
prompt_value "QUANT_GPT_LLM_MODE" "LLM policy mode" "observe_only" "false"
prompt_value "BACKTEST_MODE" "Backtest mode (cloud or local)" "cloud" "false"
prompt_value "LEAN_CLOUD_PUSH_ON_BACKTEST" "Push local code before cloud backtest" "true" "false"
prompt_value "LEAN_CLOUD_OPEN_RESULTS" "Open cloud backtest results in browser" "false" "false"
LEAN_PROJECT_DEFAULT="QualityGrowthPi"
if [[ "${QUANT_GPT_STRATEGY_MODE:-quality_growth}" == "stat_arb_graph_pairs" ]]; then
  LEAN_PROJECT_DEFAULT="GraphStatArb"
fi
prompt_value "LEAN_BACKTEST_PROJECT" "LEAN backtest project name" "$LEAN_PROJECT_DEFAULT" "false"
prompt_value "LEAN_BACKTEST_PROJECT_ID" "LEAN backtest cloud project id (optional, preferred when known)" "" "false"
prompt_value "QC_CLOUD_FILE_SYNC" "Sync LEAN workspace files to QuantConnect via API before cloud runs" "true" "false"
prompt_value "QC_CODE_SOURCE_ID" "QuantConnect code source id for lock/debug API calls" "quant_gpt_cli" "false"
prompt_value "PAPER_DEPLOYMENT_TARGET" "Paper deployment target (cloud or local)" "cloud" "false"
prompt_value "PAPER_BROKER" "Paper broker" "alpaca" "false"
prompt_value "PAPER_ENVIRONMENT" "Paper broker environment" "paper" "false"
prompt_value "PAPER_LIVE_DATA_PROVIDER" "Paper live data provider" "QuantConnect" "false"
prompt_value "PAPER_HISTORICAL_DATA_PROVIDER" "Paper historical data provider" "QuantConnect" "false"
prompt_value "LEAN_CLOUD_PUSH_ON_PAPER" "Push local code before cloud paper deploy" "true" "false"
prompt_value "LEAN_CLOUD_PAPER_NODE" "QuantConnect live node id/name for paper deploy" "" "false"
prompt_value "LEAN_CLOUD_PAPER_AUTO_RESTART" "Enable QuantConnect auto-restart for paper deploy" "true" "false"
prompt_value "LEAN_CLOUD_PAPER_NOTIFY_ORDER_EVENTS" "Enable QuantConnect order-event notifications for paper deploy" "true" "false"
prompt_value "LEAN_CLOUD_PAPER_NOTIFY_INSIGHTS" "Enable QuantConnect insight notifications for paper deploy" "false" "false"
prompt_value "LEAN_CLOUD_OPEN_PAPER" "Open cloud paper deployment results in browser" "false" "false"
prompt_value "LOCAL_FUNDAMENTALS_PROVIDER" "Local fundamentals provider stack" "massive_sec_alpha_vantage" "false"
prompt_value "LOCAL_DAILY_BARS_PROVIDER" "Local daily bars provider" "alpaca" "false"
prompt_value "STAT_ARB_ML_FILTER_MODE" "Stat-arb ML filter mode (embedded_scorecard or object_store_model)" "embedded_scorecard" "false"
prompt_value "STAT_ARB_ML_MODEL_VERSION" "Stat-arb ML model version" "ensemble_v1" "false"
prompt_value "STAT_ARB_OBJECT_STORE_MODEL_KEY" "Stat-arb Object Store model key (required when using object_store_model)" "" "false"
prompt_value "STAT_ARB_LOCAL_MODEL_PATH" "Stat-arb local model path" "/mnt/nvme_data/shared/quant_gpt/data/models/stat_arb/ensemble.joblib" "false"
prompt_value "STAT_ARB_FEATURE_SCHEMA_VERSION" "Stat-arb feature schema version" "stat_arb_v1" "false"
prompt_value "STAT_ARB_ML_FALLBACK_MODE" "Stat-arb ML fallback mode" "embedded_scorecard" "false"
prompt_value "QUANTCONNECT_USER_ID" "QuantConnect user id" "" "true"
prompt_value "QUANTCONNECT_API_TOKEN" "QuantConnect API token" "" "true"
prompt_value "LEAN_ORGANIZATION_ID" "LEAN organization id (QuantConnect org id, not your personal name)" "" "false"
prompt_value "LEAN_DATA_DIRECTORY" "LEAN data directory" "/mnt/nvme_data/shared/quant_gpt/data/lean" "false"
prompt_value "ALPACA_API_KEY" "Alpaca API key" "" "true"
prompt_value "ALPACA_API_SECRET" "Alpaca API secret" "" "true"
prompt_value "ALPACA_ENVIRONMENT" "Alpaca environment" "paper" "false"
prompt_value "ALPACA_TRADING_BASE_URL" "Alpaca trading base URL" "https://paper-api.alpaca.markets" "false"
prompt_value "ALPACA_MARKET_DATA_BASE_URL" "Alpaca market data base URL" "https://data.alpaca.markets" "false"
prompt_value "ALPACA_DATA_FEED" "Alpaca market data feed" "iex" "false"
prompt_value "MASSIVE_API_KEY" "Massive API key (formerly Polygon.io)" "" "true"
prompt_value "MASSIVE_BASE_URL" "Massive base URL" "https://api.massive.com" "false"
prompt_value "MASSIVE_FUNDAMENTALS_CACHE_PATH" "Massive fundamentals cache path" "/mnt/nvme_data/shared/quant_gpt/data/market_cache/massive/fundamentals_snapshot.jsonl" "false"
prompt_value "ALPHA_VANTAGE_API_KEY" "Alpha Vantage API key" "" "true"
prompt_value "ALPHA_VANTAGE_BASE_URL" "Alpha Vantage base URL" "https://www.alphavantage.co/query" "false"
prompt_value "ALPHA_VANTAGE_FUNDAMENTALS_CACHE_PATH" "Alpha Vantage fundamentals cache path" "/mnt/nvme_data/shared/quant_gpt/data/market_cache/alpha_vantage/fundamentals_snapshot.jsonl" "false"
prompt_value "SEC_API_USER_AGENT" "SEC API user agent" "" "false"
prompt_value "SEC_FUNDAMENTALS_CACHE_PATH" "SEC fundamentals cache path" "/mnt/nvme_data/shared/quant_gpt/data/market_cache/sec/fundamentals_snapshot.jsonl" "false"
prompt_value "GEMINI_API_KEY" "Gemini API key" "" "true"
prompt_value "GEMINI_MODEL_ID" "Gemini model id" "gemini-3.1-flash-lite-preview" "false"
prompt_value "GEMINI_FALLBACK_MODEL_ID" "Gemini fallback model id" "gemini-3.1-flash" "false"
prompt_value "GOOGLE_CLOUD_PROJECT" "Google Cloud project" "" "false"
prompt_value "GOOGLE_CLOUD_LOCATION" "Google Cloud location" "" "false"
prompt_value "GEMINI_TIMEOUT_SECONDS" "Gemini timeout seconds" "12" "false"
prompt_value "GEMINI_MAX_RETRIES" "Gemini max retries" "2" "false"
prompt_value "BROKER_MODE" "Broker mode" "paper" "false"
prompt_value "IBKR_HOST" "IBKR host" "127.0.0.1" "false"
prompt_value "IBKR_PORT" "IBKR port" "7497" "false"
prompt_value "IBKR_ACCOUNT" "IBKR account id" "" "true"
prompt_value "IBKR_CLIENT_ID" "IBKR client id" "101" "false"
prompt_value "LLM_BUDGET_USD_DAILY" "Daily LLM budget USD" "5.00" "false"
prompt_value "LLM_ESTIMATED_REQUEST_COST_USD" "Estimated LLM request cost USD" "0.001" "false"
prompt_value "LLM_MAX_SYMBOLS_PER_BATCH" "Max symbols per LLM batch" "20" "false"
prompt_value "LLM_CACHE_TTL_MINUTES" "LLM cache TTL minutes" "240" "false"
prompt_value "LLM_REQUIRE_MANUAL_REVIEW" "Require manual review on LLM reduce_size" "false" "false"
prompt_value "NEWS_PROVIDER_MODE" "News provider mode" "composite" "false"
prompt_value "NEWS_FEED_PATH" "Local news feed path" "/mnt/nvme_data/shared/quant_gpt/data/news_cache/news_feed.jsonl" "false"

mv "$TMP_FILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"
printf 'Wrote %s with permissions 600\n' "$ENV_FILE"
