#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
TEMPLATE_FILE="$PROJECT_ROOT/.env.template"
TMP_FILE="$(mktemp)"

cleanup() {
  rm -f "$TMP_FILE"
}
trap cleanup EXIT

if [[ ! -f "$TEMPLATE_FILE" ]]; then
  printf 'Missing template file: %s\n' "$TEMPLATE_FILE" >&2
  exit 1
fi

get_existing_value() {
  local key="$1"
  if [[ -f "$ENV_FILE" ]]; then
    grep -E "^${key}=" "$ENV_FILE" | tail -n1 | cut -d'=' -f2- || true
  fi
}

prompt_value() {
  local key="$1"
  local prompt="$2"
  local default="$3"
  local secret="$4"
  local existing value

  existing="$(get_existing_value "$key")"
  value="$existing"

  if [[ -n "$existing" ]]; then
    read -r -p "$key already exists. Keep current value? [Y/n]: " keep
    if [[ ! "$keep" =~ ^[Nn]$ ]]; then
      printf '%s=%s\n' "$key" "$existing" >> "$TMP_FILE"
      return
    fi
  fi

  if [[ "$secret" == "true" ]]; then
    read -r -s -p "$prompt [$default]: " value
    printf '\n'
  else
    read -r -p "$prompt [$default]: " value
  fi

  if [[ -z "$value" ]]; then
    value="$default"
  fi
  printf '%s=%s\n' "$key" "$value" >> "$TMP_FILE"
}

printf '# Generated by scripts/setup_env.sh on %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "$TMP_FILE"

prompt_value "QUANT_GPT_ENV" "Environment name" "dev" "false"
prompt_value "QUANT_GPT_RUNTIME_ROOT" "Runtime root path" "/mnt/nvme_data/shared/quant_gpt" "false"
prompt_value "QUANT_GPT_STATE_DB" "SQLite DB path" "/mnt/nvme_data/shared/quant_gpt/state/quant_gpt.db" "false"
prompt_value "QUANT_GPT_LOG_LEVEL" "Log level" "DEBUG" "false"
prompt_value "QUANT_GPT_PROVIDER_MODE" "Provider mode" "quantconnect_local" "false"
prompt_value "QUANT_GPT_ENABLE_LLM" "Enable LLM subsystem" "true" "false"
prompt_value "QUANT_GPT_LLM_MODE" "LLM policy mode" "observe_only" "false"
prompt_value "QUANTCONNECT_USER_ID" "QuantConnect user id" "" "true"
prompt_value "QUANTCONNECT_API_TOKEN" "QuantConnect API token" "" "true"
prompt_value "LEAN_ORGANIZATION_ID" "LEAN organization id" "" "false"
prompt_value "LEAN_DATA_DIRECTORY" "LEAN data directory" "/mnt/nvme_data/shared/quant_gpt/data/lean" "false"
prompt_value "POLYGON_API_KEY" "Polygon API key" "" "true"
prompt_value "POLYGON_BASE_URL" "Polygon base URL" "https://api.polygon.io" "false"
prompt_value "GEMINI_API_KEY" "Gemini API key" "" "true"
prompt_value "GEMINI_MODEL_ID" "Gemini model id" "gemini-3.1-flash-lite-preview" "false"
prompt_value "GEMINI_FALLBACK_MODEL_ID" "Gemini fallback model id" "gemini-3.1-flash" "false"
prompt_value "GOOGLE_CLOUD_PROJECT" "Google Cloud project" "" "false"
prompt_value "GOOGLE_CLOUD_LOCATION" "Google Cloud location" "" "false"
prompt_value "GEMINI_TIMEOUT_SECONDS" "Gemini timeout seconds" "12" "false"
prompt_value "GEMINI_MAX_RETRIES" "Gemini max retries" "2" "false"
prompt_value "BROKER_MODE" "Broker mode" "paper" "false"
prompt_value "IBKR_HOST" "IBKR host" "127.0.0.1" "false"
prompt_value "IBKR_PORT" "IBKR port" "7497" "false"
prompt_value "IBKR_ACCOUNT" "IBKR account id" "" "true"
prompt_value "IBKR_CLIENT_ID" "IBKR client id" "101" "false"
prompt_value "LLM_BUDGET_USD_DAILY" "Daily LLM budget USD" "5.00" "false"
prompt_value "LLM_ESTIMATED_REQUEST_COST_USD" "Estimated LLM request cost USD" "0.001" "false"
prompt_value "LLM_MAX_SYMBOLS_PER_BATCH" "Max symbols per LLM batch" "20" "false"
prompt_value "LLM_CACHE_TTL_MINUTES" "LLM cache TTL minutes" "240" "false"
prompt_value "LLM_REQUIRE_MANUAL_REVIEW" "Require manual review on LLM reduce_size" "false" "false"
prompt_value "NEWS_PROVIDER_MODE" "News provider mode" "file" "false"
prompt_value "NEWS_FEED_PATH" "Local news feed path" "/mnt/nvme_data/shared/quant_gpt/data/news_cache/news_feed.jsonl" "false"

mv "$TMP_FILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"
printf 'Wrote %s with permissions 600\n' "$ENV_FILE"
